version: "3.9"

x-django-env: &django-env
  DJANGO_DEBUG: false
  DJANGO_SETTINGS_MODULE: qb.settings
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  DB_ENGINE: django.db.backends.postgresql
  DB_NAME: ${DATABASE_DB}
  DB_USER: ${DATABASE_USER}
  DB_PASSWORD: ${DATABASE_PASSWORD}
  DB_HOST: ${DATABASE_HOST}
  DB_PORT: ${DATABASE_PORT}

x-app-image: &app-image ${IMAGE_TAG}

x-common-labels: &common-labels
  observability.app: qb
  observability.environment: ${SHARED_ENV}

networks:
  default:
    name: ${SHARED_NETWORK}
    external: true

services:
  qb:
    image: *app-image
    container_name: ${SHARED_ENV}_qb_app
    labels:
      <<: *common-labels
      observability.component: api
    environment:
      <<: *django-env
    ports:
      - "${API_PORT}:8000"
    restart: always
