version: "3.9"

x-postgres-env: &postgres-env
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

x-django-env: &django-env
  DJANGO_DEBUG: false
  DJANGO_SETTINGS_MODULE: qb.settings
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  DB_ENGINE: django.db.backends.postgresql
  DB_NAME: qb
  DB_USER: postgres
  DB_PASSWORD: ${POSTGRES_PASSWORD}
  DB_HOST: qb_postgres
  DB_PORT: 5432

x-django-full-env: &django-full-env
  <<: [*django-env, *postgres-env]

x-app-image: &app-image ${IMAGE_TAG}

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  static:

services:
  postgres:
    image: postgres:16-alpine
    container_name: qb_postgres
    restart: always
    environment:
      <<: *postgres-env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  qb:
    image: *app-image
    container_name: qb_app
    environment:
      <<: *django-full-env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8012:8000"
    networks:
      - backend
    restart: always
