# Generated by Django 6.0.6 on 2026-07-12 12:36

import base.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFieldType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BalanceEntryType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExecutionProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('receipt', models.CharField(blank=True, max_length=120)),
                ('amount_transacted_minor', models.BigIntegerField()),
                ('total_balance_minor', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='ACTIVE', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('balance_entry_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_logs', to='ledger.balanceentrytype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_logs', to='ledger.state')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RuleProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField()),
                ('sleep_seconds', models.PositiveSmallIntegerField(default=0)),
                ('execution_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ledger.executionprofile')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_profiles', to='ledger.state')),
            ],
            options={
                'ordering': ('execution_profile__name', 'order'),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='ledger.state')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='executionprofile',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_profiles', to='ledger.state'),
        ),
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_types', to='ledger.state')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BalanceLogEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('amount_transacted_minor', models.BigIntegerField()),
                ('balance_before_minor', models.BigIntegerField()),
                ('balance_after_minor', models.BigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account_field_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_log_entries', to='ledger.accountfieldtype')),
                ('balance_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.balancelog')),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_log_entries', to='ledger.entrytype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_log_entries', to='ledger.state')),
            ],
            options={
                'ordering': ('balance_log', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='balanceentrytype',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_entry_types', to='ledger.state'),
        ),
        migrations.AddField(
            model_name='accountfieldtype',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_field_types', to='ledger.state'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('USER', 'User'), ('ORGANIZATION', 'Organization'), ('SYSTEM', 'System')], max_length=24)),
                ('account_kind', models.CharField(choices=[('PRIMARY', 'Primary'), ('VAULT', 'Vault')], default='PRIMARY', max_length=20)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('current_balance_minor', models.BigIntegerField(default=0)),
                ('reserved_balance_minor', models.BigIntegerField(default=0)),
                ('available_balance_minor', models.BigIntegerField(default=0)),
                ('uncleared_balance_minor', models.BigIntegerField(default=0)),
                ('charge_balance_minor', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_accounts', to='base.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_accounts', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='ledger.state')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('PAY_IN', 'Pay In'), ('PAY_OUT', 'Pay Out'), ('INTERNAL', 'Internal')], max_length=16)),
                ('internal_reference', models.CharField(max_length=100, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('transaction_receipt', models.CharField(blank=True, max_length=120)),
                ('confirmation_key', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PROCESSING', max_length=16)),
                ('source_ip', models.CharField(blank=True, max_length=45)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.account')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.paymentmethod')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.state')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('STK_PUSH', 'STK Push'), ('PAY_IN', 'Pay In'), ('PAYOUT', 'Payout')], max_length=20)),
                ('originator_ref', models.CharField(max_length=100, unique=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=16)),
                ('sandbox', models.BooleanField(default=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('last_query_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='ledger.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='balancelog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_logs', to='ledger.transaction'),
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('simple_name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('is_viewable', models.BooleanField(default=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_types', to='ledger.state')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.transactiontype'),
        ),
        migrations.CreateModel(
            name='RuleProfileCommand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField()),
                ('rule_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='ledger.ruleprofile')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_profile_commands', to='ledger.state')),
            ],
            options={
                'ordering': ('rule_profile__execution_profile__name', 'rule_profile__order', 'order'),
                'constraints': [models.UniqueConstraint(fields=('rule_profile', 'order'), name='uniq_rule_profile_command_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='ruleprofile',
            constraint=models.UniqueConstraint(fields=('execution_profile', 'name'), name='uniq_rule_profile_execution_name'),
        ),
        migrations.AddConstraint(
            model_name='ruleprofile',
            constraint=models.UniqueConstraint(fields=('execution_profile', 'order'), name='uniq_rule_profile_execution_order'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner_type', 'account_kind', 'currency'], name='ledger_acco_owner_t_ad38f1_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['status', 'created_at'], name='ledger_acco_status_ae5b4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'account_kind', 'currency'), name='uniq_account_user_kind_currency'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'account_kind', 'currency'), name='uniq_account_org_kind_currency'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('owner_type', 'USER'), ('user__isnull', False)), models.Q(('organization__isnull', False), ('owner_type', 'ORGANIZATION'), ('user__isnull', True)), models.Q(('organization__isnull', True), ('owner_type', 'SYSTEM'), ('user__isnull', True)), _connector='OR'), name='account_single_owner'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance_minor__gte', 0)), name='account_available_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_balance_minor__gte', 0)), name='account_reserved_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('uncleared_balance_minor__gte', 0)), name='account_uncleared_not_negative'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['status', 'created_at'], name='ledger_paym_status_c0ac2f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['operation', 'created_at'], name='ledger_paym_operati_602971_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='ledger_tran_status_676b94_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'created_at'], name='ledger_tran_account_7efd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='ledger_tran_transac_9ae3ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('account', 'idempotency_key'), name='uniq_transaction_account_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='transaction_amount_positive'),
        ),
    ]
