# Generated by Django 6.0.6 on 2026-07-06 18:09

import base.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0013_walletbalance_wallethold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('TOP_UP', 'Top Up'), ('WITHDRAWAL', 'Withdrawal'), ('ADJUSTMENT', 'Adjustment')], max_length=32)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=16)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('balance_before_minor', models.BigIntegerField()),
                ('balance_after_minor', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'ledger_entries',
            },
        ),
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('USER', 'User'), ('ORGANIZATION', 'Organization'), ('SYSTEM', 'System')], max_length=24)),
                ('wallet_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('VAULT', 'Vault')], default='PRIMARY', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('available_balance_minor', models.BigIntegerField(default=0)),
                ('current_balance_minor', models.BigIntegerField(default=0)),
                ('reserved_balance_minor', models.BigIntegerField(default=0)),
                ('uncleared_balance_minor', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to='base.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_accounts',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntryLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('balance_field', models.CharField(choices=[('available', 'Available'), ('current', 'Current'), ('reserved', 'Reserved'), ('uncleared', 'Uncleared')], max_length=16)),
                ('delta_minor', models.BigIntegerField()),
                ('balance_before_minor', models.BigIntegerField()),
                ('balance_after_minor', models.BigIntegerField()),
                ('reason', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ledger.ledgerentry')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_logs', to='ledger.walletaccount')),
            ],
            options={
                'db_table': 'ledger_entry_logs',
                'ordering': ['entry', 'sequence', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.walletaccount'),
        ),
        migrations.AddIndex(
            model_name='walletaccount',
            index=models.Index(fields=['owner_type', 'wallet_type', 'currency'], name='wallet_acco_owner_t_683cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='walletaccount',
            index=models.Index(fields=['status', 'created_at'], name='wallet_acco_status_051436_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'wallet_type', 'currency'), name='uniq_wallet_account_user_type_currency'),
        ),
        migrations.AddConstraint(
            model_name='walletaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'wallet_type', 'currency'), name='uniq_wallet_account_org_type_currency'),
        ),
        migrations.AddConstraint(
            model_name='walletaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('owner_type', 'USER'), ('user__isnull', False)), models.Q(('organization__isnull', False), ('owner_type', 'ORGANIZATION'), ('user__isnull', True)), models.Q(('organization__isnull', True), ('owner_type', 'SYSTEM'), ('user__isnull', True)), _connector='OR'), name='wallet_account_single_owner'),
        ),
        migrations.AddConstraint(
            model_name='walletaccount',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance_minor__gte', 0)), name='wallet_account_available_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='walletaccount',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_balance_minor__gte', 0)), name='wallet_account_reserved_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='walletaccount',
            constraint=models.CheckConstraint(condition=models.Q(('uncleared_balance_minor__gte', 0)), name='wallet_account_uncleared_not_negative'),
        ),
        migrations.AddIndex(
            model_name='ledgerentrylog',
            index=models.Index(fields=['account', 'created_at'], name='ledger_entr_account_64129c_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentrylog',
            index=models.Index(fields=['entry', 'sequence'], name='ledger_entr_entry_i_71e25e_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentrylog',
            constraint=models.UniqueConstraint(fields=('entry', 'sequence', 'balance_field'), name='uniq_ledger_log_step_field'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'created_at'], name='ledger_entr_account_14b5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaction_type', 'created_at'], name='ledger_entr_transac_49808c_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('account', 'idempotency_key'), name='uniq_wallet_account_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='ledger_entry_amount_positive'),
        ),
    ]
