# Generated by Django 6.0.6 on 2026-07-12 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationapikey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integration_api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrationapikey',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_api_keys', to='base.organization'),
        ),
        migrations.AddField(
            model_name='integrationapikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_api_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
