# Generated by Django 6.0.6 on 2026-07-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eusers', '0004_user_account_type_service_provider'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginotp',
            new_name='eusers_logi_user_id_de6539_idx',
            old_name='eusers_logi_user_id_17f33e_idx',
        ),
    ]
