# Generated by Django 6.0.6 on 2026-07-03 11:54

import base.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('TRANSACTION_HISTORY', 'Transaction History'), ('WALLET_STATEMENT', 'Wallet Statement')], max_length=32)),
                ('file_format', models.CharField(choices=[('CSV', 'CSV'), ('PDF', 'PDF'), ('XLSX', 'XLSX')], default='CSV', max_length=8)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('GENERATED', 'Generated'), ('FAILED', 'Failed')], default='REQUESTED', max_length=16)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='base.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
