# Generated by Codex on 2026-07-06

from django.db import migrations, models

from audit.models import build_audit_description


def backfill_descriptions(apps, schema_editor):
    AuditLog = apps.get_model("audit", "AuditLog")
    for log in AuditLog.objects.filter(description="").iterator():
        log.description = build_audit_description(log.action, log.target_type, log.target_id, log.metadata)
        log.save(update_fields=["description"])


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(backfill_descriptions, migrations.RunPython.noop),
    ]
