# Generated by Django 6.0.6 on 2026-07-12 12:36

import base.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDirectory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CircuitBreakerState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('CLOSED', 'Closed'), ('OPEN', 'Open'), ('HALF_OPEN', 'Half Open')], default='CLOSED', max_length=16)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('opened_until', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=12)),
                ('path', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=16)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('tax_identification_document', models.FileField(blank=True, upload_to='organization_kyc/tax_identification/')),
                ('business_registration_certificate', models.FileField(blank=True, upload_to='organization_kyc/business_registration/')),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('default_currency', models.CharField(default='KES', max_length=3)),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MAKER', 'Maker'), ('CHECKER', 'Checker'), ('VIEWER', 'Viewer')], max_length=16)),
                ('token', models.CharField(db_index=True, max_length=96, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REVOKED', 'Revoked')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MAKER', 'Maker'), ('CHECKER', 'Checker'), ('VIEWER', 'Viewer')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, max_length=64)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('payee_type', models.CharField(choices=[('PAYBILL', 'M-Pesa Paybill'), ('TILL', 'M-Pesa Till'), ('MOBILE', 'Mobile Send Money'), ('BANK', 'Bank Account')], max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('account_reference', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('paybill_number', models.CharField(blank=True, max_length=20)),
                ('till_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('expense_category', models.CharField(default='general', max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayeePreset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('payee_type', models.CharField(choices=[('PAYBILL', 'M-Pesa Paybill'), ('TILL', 'M-Pesa Till'), ('MOBILE', 'Mobile Send Money'), ('BANK', 'Bank Account')], max_length=16)),
                ('paybill_number', models.CharField(blank=True, max_length=20)),
                ('till_number', models.CharField(blank=True, max_length=20)),
                ('expense_category', models.CharField(default='general', max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('batch_kind', models.CharField(choices=[('INDIVIDUAL_MONTHLY', 'Individual Monthly'), ('INDIVIDUAL_ADHOC', 'Individual Ad Hoc'), ('CORPORATE_UPLOAD', 'Corporate Upload')], max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('payment_mode', models.CharField(choices=[('WALLET', 'Wallet'), ('STK', 'STK Push')], max_length=10)),
                ('scheduled_for', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source_file_name', models.CharField(blank=True, max_length=255)),
                ('total_amount_minor', models.BigIntegerField(default=0)),
                ('fee_amount_minor', models.BigIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentInstruction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_type', models.CharField(choices=[('PAYBILL', 'M-Pesa Paybill'), ('TILL', 'M-Pesa Till'), ('MOBILE', 'Mobile Send Money'), ('BANK', 'Bank Account')], max_length=16)),
                ('destination', models.JSONField(default=dict)),
                ('amount_minor', models.BigIntegerField()),
                ('fee_amount_minor', models.BigIntegerField(default=0)),
                ('category', models.CharField(default='general', max_length=64)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('microservice_request_id', models.CharField(blank=True, max_length=120)),
                ('microservice_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.BigIntegerField()),
                ('day_of_month', models.PositiveSmallIntegerField()),
                ('interval_months', models.PositiveSmallIntegerField(default=1)),
                ('next_due_date', models.DateField(default=django.utils.timezone.localdate)),
                ('requires_approval', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64)),
                ('reference', models.CharField(max_length=120)),
                ('internal_reference', models.CharField(blank=True, max_length=120)),
                ('expected_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('actual_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(db_index=True, max_length=64)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=64)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(blank=True, max_length=32)),
                ('microservice_request_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
