# Generated by Django 6.0.6 on 2026-07-03 11:54

import base.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('default_currency', models.CharField(default='KES', max_length=3)),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, max_length=64)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('payee_type', models.CharField(choices=[('PAYBILL', 'M-Pesa Paybill'), ('TILL', 'M-Pesa Till'), ('MOBILE', 'Mobile Send Money'), ('BANK', 'Bank Account')], max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('account_reference', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('paybill_number', models.CharField(blank=True, max_length=20)),
                ('till_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('expense_category', models.CharField(default='general', max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('batch_kind', models.CharField(choices=[('INDIVIDUAL_MONTHLY', 'Individual Monthly'), ('CORPORATE_UPLOAD', 'Corporate Upload')], max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('payment_mode', models.CharField(choices=[('WALLET', 'Wallet'), ('STK', 'STK Push')], max_length=10)),
                ('scheduled_for', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source_file_name', models.CharField(blank=True, max_length=255)),
                ('total_amount_minor', models.BigIntegerField(default=0)),
                ('fee_amount_minor', models.BigIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentInstruction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_type', models.CharField(choices=[('PAYBILL', 'M-Pesa Paybill'), ('TILL', 'M-Pesa Till'), ('MOBILE', 'Mobile Send Money'), ('BANK', 'Bank Account')], max_length=16)),
                ('destination', models.JSONField(default=dict)),
                ('amount_minor', models.BigIntegerField()),
                ('category', models.CharField(default='general', max_length=64)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.BigIntegerField()),
                ('day_of_month', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('USER', 'User'), ('ORGANIZATION', 'Organization')], max_length=20)),
                ('wallet_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('VAULT', 'Vault')], default='PRIMARY', max_length=20)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('available_balance_minor', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WalletLedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('TOP_UP', 'Top Up'), ('TRANSFER_TO_VAULT', 'Transfer To Vault'), ('TRANSFER_FROM_VAULT', 'Transfer From Vault'), ('DISBURSEMENT', 'Disbursement'), ('ADJUSTMENT', 'Adjustment')], max_length=32)),
                ('amount_minor', models.BigIntegerField()),
                ('balance_after_minor', models.BigIntegerField()),
                ('reference', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MAKER', 'Maker'), ('CHECKER', 'Checker'), ('VIEWER', 'Viewer')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='base.organization')),
            ],
        ),
    ]
