# Generated by Django 6.0.6 on 2026-07-12 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationinvite',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_organization_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationinvite',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='base.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='base.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payees', to='base.organization'),
        ),
        migrations.AddField(
            model_name='payee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payee',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payees', to='base.payeepreset'),
        ),
        migrations.AddField(
            model_name='paymentbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentbatch',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_batches', to='base.organization'),
        ),
        migrations.AddField(
            model_name='paymentbatch',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentbatch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentinstruction',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='base.paymentbatch'),
        ),
        migrations.AddField(
            model_name='paymentinstruction',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions', to='base.payee'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='base.payee'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationexception',
            constraint=models.UniqueConstraint(fields=('source', 'reference'), name='uniq_reconciliation_source_reference'),
        ),
        migrations.AddField(
            model_name='transactionevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('user', 'key', 'method', 'path'), name='uniq_user_idempotency_scope'),
        ),
        migrations.AddConstraint(
            model_name='organizationinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('organization', 'email'), name='uniq_pending_org_invite_email'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='uniq_org_membership'),
        ),
        migrations.AddConstraint(
            model_name='paymentschedule',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_month__gte', 1), ('day_of_month__lte', 31)), name='schedule_day_between_1_31'),
        ),
        migrations.AddConstraint(
            model_name='paymentschedule',
            constraint=models.CheckConstraint(condition=models.Q(('interval_months__gte', 1)), name='schedule_interval_months_gte_1'),
        ),
        migrations.AddIndex(
            model_name='transactionevent',
            index=models.Index(fields=['aggregate_type', 'aggregate_id', 'created_at'], name='tx_event_aggregate_created'),
        ),
    ]
