# Generated by Codex on 2026-07-05

import base.utils
import django.db.models.deletion
import django.utils.timezone
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models


def default_expiry():
    return django.utils.timezone.now() + timedelta(days=7)


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationInvite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(choices=[("ADMIN", "Admin"), ("MAKER", "Maker"), ("CHECKER", "Checker"), ("VIEWER", "Viewer")], max_length=16)),
                ("token", models.CharField(db_index=True, max_length=96, unique=True)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("REVOKED", "Revoked")], default="PENDING", max_length=16)),
                ("expires_at", models.DateTimeField(default=default_expiry)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("invited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sent_organization_invites", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="base.organization")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="organizationinvite",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "PENDING")), fields=("organization", "email"), name="uniq_pending_org_invite_email"),
        ),
    ]
