# Generated by Django 6.0.6 on 2026-07-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_organization_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbatch',
            name='batch_kind',
            field=models.CharField(choices=[('INDIVIDUAL_MONTHLY', 'Individual Monthly'), ('INDIVIDUAL_ADHOC', 'Individual Ad Hoc'), ('CORPORATE_UPLOAD', 'Corporate Upload')], max_length=32),
        ),
    ]
