# Generated by Django 6.0.6 on 2026-07-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_organizationinvite'),
        ('base', '0007_alter_paymentbatch_batch_kind'),
    ]

    operations = [
    ]
