# Generated by Codex on 2026-07-05

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_merge_20260705_1853"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name", "created_at"],
                "abstract": False,
            },
        ),
    ]
