# Generated by Codex on 2026-07-05

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_expensecategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDirectory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name", "code"],
                "abstract": False,
            },
        ),
    ]
