# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_bankdirectory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationinvite",
            name="expires_at",
            field=models.DateTimeField(),
        ),
    ]
