# Generated by Django 6.0.6 on 2026-07-06 12:46

import base.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_circuitbreakerstate_ledgertransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_balance_minor', models.BigIntegerField(default=0)),
                ('uncleared_balance_minor', models.BigIntegerField(default=0)),
                ('reserved_balance_minor', models.BigIntegerField(default=0)),
                ('available_balance_minor', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletHold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('CAPTURED', 'Captured'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=16)),
                ('reason', models.CharField(max_length=64)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='walletledgerentry',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletledgerentry',
            name='clearing_status',
            field=models.CharField(choices=[('CLEARED', 'Cleared'), ('UNCLEARED', 'Uncleared')], default='CLEARED', max_length=16),
        ),
        migrations.AddIndex(
            model_name='walletledgerentry',
            index=models.Index(fields=['wallet', 'created_at'], name='base_wallet_wallet__846f17_idx'),
        ),
        migrations.AddIndex(
            model_name='walletledgerentry',
            index=models.Index(fields=['wallet', 'clearing_status'], name='base_wallet_wallet__483ff4_idx'),
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='balance', to='base.wallet'),
        ),
        migrations.AddField(
            model_name='wallethold',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capturing_holds', to='base.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='wallethold',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='base.wallet'),
        ),
        migrations.AddIndex(
            model_name='wallethold',
            index=models.Index(fields=['wallet', 'status'], name='base_wallet_wallet__ecbf01_idx'),
        ),
        migrations.AddIndex(
            model_name='wallethold',
            index=models.Index(fields=['status', 'expires_at'], name='base_wallet_status_abb0f1_idx'),
        ),
    ]
