# Generated by Django 6.0.6 on 2026-07-03 11:54

import base.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(choices=[('T_MINUS_3', 'T Minus 3'), ('DUE_TODAY', 'Due Today'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILURE', 'Payment Failure'), ('APPROVAL_REQUEST', 'Approval Request'), ('BATCH_APPROVED', 'Batch Approved'), ('BATCH_REJECTED', 'Batch Rejected')], max_length=32)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=8)),
                ('system', models.CharField(default='route', max_length=64)),
                ('provider_template', models.CharField(max_length=64)),
                ('subject_template', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('default_context', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event_type', 'channel'), name='uniq_notification_template_event_channel')],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=base.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=8)),
                ('event_type', models.CharField(choices=[('T_MINUS_3', 'T Minus 3'), ('DUE_TODAY', 'Due Today'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILURE', 'Payment Failure'), ('APPROVAL_REQUEST', 'Approval Request'), ('BATCH_APPROVED', 'Batch Approved'), ('BATCH_REJECTED', 'Batch Rejected')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('unique_identifier', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='notifications.notificationtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
