# Generated by Django 6.0.6 on 2026-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_seed_corporate_email_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='event_type',
            field=models.CharField(choices=[('T_MINUS_3', 'T Minus 3'), ('DUE_TODAY', 'Due Today'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILURE', 'Payment Failure'), ('APPROVAL_REQUEST', 'Approval Request'), ('BATCH_APPROVED', 'Batch Approved'), ('BATCH_REJECTED', 'Batch Rejected'), ('SELF_ONBOARDING', 'Self Onboarding'), ('LOGIN_OTP', 'Login OTP'), ('LOGIN_SUCCESS', 'Login Success'), ('ORGANIZATION_INVITE', 'Organization Invite')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('T_MINUS_3', 'T Minus 3'), ('DUE_TODAY', 'Due Today'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILURE', 'Payment Failure'), ('APPROVAL_REQUEST', 'Approval Request'), ('BATCH_APPROVED', 'Batch Approved'), ('BATCH_REJECTED', 'Batch Rejected'), ('SELF_ONBOARDING', 'Self Onboarding'), ('LOGIN_OTP', 'Login OTP'), ('LOGIN_SUCCESS', 'Login Success'), ('ORGANIZATION_INVITE', 'Organization Invite')], max_length=32),
        ),
    ]
