from django.urls import path

from .views import (
    approvals_view,
    account_contexts_view,
    banks_view,
    batch_detail_view,
    batches_view,
    change_password_view,
    corporate_batch_approve_view,
    corporate_batch_reject_view,
    corporate_batch_submit_view,
    corporate_batch_upload_view,
    dashboard_view,
    expense_categories_view,
    health_view,
    integration_api_key_revoke_view,
    integration_api_keys_view,
    login_view,
    me_view,
    organization_detail_view,
    organization_invite_accept_view,
    organization_invites_view,
    organization_member_detail_view,
    organizations_view,
    organization_members_view,
    pay_all_view,
    quick_pay_view,
    payee_detail_view,
    payee_presets_view,
    payees_view,
    pesaway_results_view,
    report_exports_view,
    register_view,
    schedule_detail_view,
    schedules_view,
    transaction_report_view,
    transaction_statement_pdf_view,
    transaction_summary_view,
    wallet_ledger_view,
    wallet_summary_view,
    wallet_topup_view,
    wallet_vault_view,
    wallet_withdrawal_view,
)

urlpatterns = [
    path("health/", health_view, name="health"),
    path("auth/register/", register_view, name="register"),
    path("auth/login/", login_view, name="login"),
    path("auth/me/", me_view, name="me"),
    path("auth/change-password/", change_password_view, name="change-password"),
    path("integrations/api-keys/", integration_api_keys_view, name="integration-api-keys"),
    path("integrations/api-keys/<uuid:api_key_id>/revoke/", integration_api_key_revoke_view, name="integration-api-key-revoke"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("account-contexts/", account_contexts_view, name="account-contexts"),
    path("organizations/", organizations_view, name="organizations"),
    path("organizations/<uuid:organization_id>/", organization_detail_view, name="organization-detail"),
    path("organizations/<uuid:organization_id>/members/", organization_members_view, name="organization-members"),
    path("organizations/<uuid:organization_id>/invites/", organization_invites_view, name="organization-invites"),
    path("organization-invites/accept/", organization_invite_accept_view, name="organization-invite-accept"),
    path(
        "organizations/<uuid:organization_id>/members/<uuid:membership_id>/",
        organization_member_detail_view,
        name="organization-member-detail",
    ),
    path("payee-presets/", payee_presets_view, name="payee-presets"),
    path("payee-categories/", expense_categories_view, name="payee-categories"),
    path("banks/", banks_view, name="banks"),
    path("payees/", payees_view, name="payees"),
    path("payees/<uuid:payee_id>/", payee_detail_view, name="payee-detail"),
    path("schedules/", schedules_view, name="schedules"),
    path("schedules/<uuid:schedule_id>/", schedule_detail_view, name="schedule-detail"),
    path("wallets/", wallet_summary_view, name="wallet-summary"),
    path("wallets/ledger/", wallet_ledger_view, name="wallet-ledger"),
    path("wallets/topups/", wallet_topup_view, name="wallet-topups"),
    path("wallets/vault/", wallet_vault_view, name="wallet-vault"),
    path("wallets/withdrawals/", wallet_withdrawal_view, name="wallet-withdrawals"),
    path("payments/pay-all/", pay_all_view, name="pay-all"),
    path("payments/quick-pay/", quick_pay_view, name="quick-pay"),
    path("corporate/batches/upload/", corporate_batch_upload_view, name="corporate-batch-upload"),
    path("corporate/batches/<uuid:batch_id>/submit/", corporate_batch_submit_view, name="corporate-batch-submit"),
    path("corporate/batches/<uuid:batch_id>/approve/", corporate_batch_approve_view, name="corporate-batch-approve"),
    path("corporate/batches/<uuid:batch_id>/reject/", corporate_batch_reject_view, name="corporate-batch-reject"),
    path("approvals/", approvals_view, name="approvals"),
    path("batches/", batches_view, name="batches"),
    path("batches/<uuid:batch_id>/", batch_detail_view, name="batch-detail"),
    path("reports/transactions.csv", transaction_report_view, name="transaction-report"),
    path("reports/transactions.statement.pdf", transaction_statement_pdf_view, name="transaction-statement-pdf"),
    path("reports/transactions/summary/", transaction_summary_view, name="transaction-summary"),
    path("reports/exports/", report_exports_view, name="report-exports"),
    path("providers/pesaway/results/", pesaway_results_view, name="pesaway-results"),
]
